version: "3.4"

volumes:
  solr:

services:
  ftempo:
    build: .
    command: npm run watch
    volumes:
      - ${FTEMPO_STORAGE_DIR}:/storage
      - .:/app
      - /app/node_modules
    ports:
      - 8000:8000
    env_file:
      - .env
  solr:
    image: solr:8.8.2
    ports:
      - "8983:8983"
    volumes:
      - ./solr/cores:/solrconfig
      - ./solr/initdb:/docker-entrypoint-initdb.d
      - ${FTEMPO_SOLR_DATA_DIR}:/var/solr/data
    command: "solr-foreground"
