version: "3.4"

volumes:
  solr:

services:
  ftempo:
    build: .
    command: npm run watch
    volumes:
      - ${FTEMPO_STORAGE_DIR}:/storage
      - .:/app
      - /app/node_modules
    ports:
      - 8000:8000
    env_file:
      - .env
  solr:
    image: solr:8.11.1
    ports:
      - "8983:8983"
    command: solr-precreate ftempo /solrconfig/ftempo
    volumes:
      - ./solr/cores:/solrconfig
      - ${FTEMPO_SOLR_DATA_DIR}:/var/solr/data
