version: "3.4"
volumes:
  run:
  log:
  uploadrun:

services:
  ftempo:
    build: .
    command: ./start.sh
    volumes:
      - "/mnt/storage:/storage"
      - "/mnt/storage:/mnt/storage"
      - run:/app/multiservers/run
      - uploadrun:/app/run
      - log:/app/logs
    environment:
      - VIRTUAL_HOST=f-tempo.finishthings.com,search.f-tempo.org
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=f-tempo.finishthings.com,search.f-tempo.org
      - LETSENCRYPT_EMAIL=alastair@porter.net.nz
    restart: always
