version: "3.4"

volumes:
  solr:

services:
  ftempo:
    build: .
    command: npm run watch
    volumes:
      - ./storage:/storage
      - .:/app
    ports:
      - 8000:8000
  solr:
    image: solr:8.8.2
    ports:
      - "8983:8983"
    volumes:
      - ./solr/cores:/solrconfig
      - ./solr/initdb:/docker-entrypoint-initdb.d
      - solr:/var/solr/data
    command: "solr-foreground"
