version: "3.4"
services:
  ftempo:
    build: .
    command: ./start.sh
    volumes:
      - "/storage:/storage"
    ports:
      - 8000:8000
    environment:
      - VIRTUAL_HOST=uk-dev-ftempo.rism.digital
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=uk-dev-ftempo.rism.digital
      - LETSENCRYPT_EMAIL=alastair@porter.net.nz
    network_mode: bridge

