version: "3.4"

volumes:
  solr:

services:
  ftempo:
    build: .
    command: npm run multi
    volumes:
      - ./storage:/storage
      - .:/app
    ports:
      - 8000:8000
  solr:
    image: solr:8.8.2
    ports:
      - "8983:8983"
    volumes:
      - ./solr/ftempo:/myconfig
      - solr:/var/solr/data
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - ftempo
      - /myconfig